services:
  db:
    image: mysql:8.0
    container_name: clj-backend-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clj_backend_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network

  backend:
    build: .
    container_name: clj-backend-node
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=clj_backend_db
    depends_on:
      - db
    networks:
      - backend-network
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]

networks:
  backend-network:
    driver: bridge

volumes:
  db_data: